"""add_protocol_versions_and_search_queries

Revision ID: 0950fe999a8b
Revises: 1d961554c507
Create Date: 2026-02-21 00:04:09.244853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0950fe999a8b'
down_revision: Union[str, None] = '1d961554c507'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('protocol_versions',
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('research_question', sa.Text(), nullable=False),
    sa.Column('pico_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('minio_prefix', sa.Text(), nullable=True),
    sa.Column('claude_model', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_protocol_versions_review_id'), 'protocol_versions', ['review_id'], unique=False)
    op.create_table('search_queries',
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('protocol_version_id', sa.UUID(), nullable=True),
    sa.Column('pico_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('search_string', sa.Text(), nullable=True),
    sa.Column('estimated_yield', sa.Integer(), nullable=True),
    sa.Column('database', sa.Text(), nullable=True),
    sa.Column('claude_model', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['protocol_version_id'], ['protocol_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_queries_protocol_version_id'), 'search_queries', ['protocol_version_id'], unique=False)
    op.create_index(op.f('ix_search_queries_review_id'), 'search_queries', ['review_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_queries_review_id'), table_name='search_queries')
    op.drop_index(op.f('ix_search_queries_protocol_version_id'), table_name='search_queries')
    op.drop_table('search_queries')
    op.drop_index(op.f('ix_protocol_versions_review_id'), table_name='protocol_versions')
    op.drop_table('protocol_versions')
    # ### end Alembic commands ###
