"""initial_schema

Revision ID: 1d961554c507
Revises: 
Create Date: 2026-02-20 19:38:13.198908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d961554c507'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Ensure required extensions are available
    op.execute("CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\"")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('papers', 'doi',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('papers', 'status',
               existing_type=sa.TEXT(),
               server_default=None,
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('papers', 'screening_label',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('papers', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_index('idx_papers_doi', table_name='papers')
    op.drop_index('idx_papers_review_id', table_name='papers')
    op.drop_index('idx_papers_title_trgm', table_name='papers', postgresql_using='gin')
    op.create_index(op.f('ix_papers_doi'), 'papers', ['doi'], unique=False)
    op.create_index(op.f('ix_papers_review_id'), 'papers', ['review_id'], unique=False)
    op.create_index(
        'ix_papers_title_trgm', 'papers', ['title'],
        unique=False, postgresql_using='gin',
        postgresql_ops={'title': 'gin_trgm_ops'},
    )
    op.alter_column('reviews', 'status',
               existing_type=sa.TEXT(),
               server_default=None,
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('reviews', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('stats_jobs', 'job_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('stats_jobs', 'status',
               existing_type=sa.TEXT(),
               server_default=None,
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('stats_jobs', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_index(op.f('ix_stats_jobs_review_id'), 'stats_jobs', ['review_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stats_jobs_review_id'), table_name='stats_jobs')
    op.alter_column('stats_jobs', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.alter_column('stats_jobs', 'status',
               existing_type=sa.String(length=50),
               server_default=sa.text("'pending'::text"),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('stats_jobs', 'job_type',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('reviews', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.alter_column('reviews', 'status',
               existing_type=sa.String(length=50),
               server_default=sa.text("'draft'::text"),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_papers_review_id'), table_name='papers')
    op.drop_index(op.f('ix_papers_doi'), table_name='papers')
    op.create_index(
        'idx_papers_title_trgm', 'papers', ['title'],
        unique=False, postgresql_using='gin',
        postgresql_ops={'title': 'gin_trgm_ops'},
    )
    op.create_index('idx_papers_review_id', 'papers', ['review_id'], unique=False)
    op.create_index('idx_papers_doi', 'papers', ['doi'], unique=False)
    op.alter_column('papers', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.alter_column('papers', 'screening_label',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('papers', 'status',
               existing_type=sa.String(length=50),
               server_default=sa.text("'pending'::text"),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('papers', 'doi',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
