"""make_review_id_nullable_in_protocol_and_search

Revision ID: 3ef0dad316a3
Revises: 0950fe999a8b
Create Date: 2026-02-21 00:07:13.780531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ef0dad316a3'
down_revision: Union[str, None] = '0950fe999a8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('protocol_versions', 'review_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('search_queries', 'review_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('search_queries', 'review_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('protocol_versions', 'review_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
