"""add_screening_decisions

Revision ID: 54865d5dbab7
Revises: 3ef0dad316a3
Create Date: 2026-02-21 00:22:37.313258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54865d5dbab7'
down_revision: Union[str, None] = '3ef0dad316a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('screening_decisions',
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('review_id', sa.UUID(), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('duplicate_of_paper_id', sa.UUID(), nullable=True),
    sa.Column('agent1_label', sa.String(length=20), nullable=True),
    sa.Column('agent2_label', sa.String(length=20), nullable=True),
    sa.Column('final_label', sa.String(length=20), nullable=True),
    sa.Column('agent1_reasoning', sa.Text(), nullable=True),
    sa.Column('agent2_reasoning', sa.Text(), nullable=True),
    sa.Column('claude_model', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screening_decisions_final_label'), 'screening_decisions', ['final_label'], unique=False)
    op.create_index(op.f('ix_screening_decisions_paper_id'), 'screening_decisions', ['paper_id'], unique=False)
    op.create_index(op.f('ix_screening_decisions_review_id'), 'screening_decisions', ['review_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_screening_decisions_review_id'), table_name='screening_decisions')
    op.drop_index(op.f('ix_screening_decisions_paper_id'), table_name='screening_decisions')
    op.drop_index(op.f('ix_screening_decisions_final_label'), table_name='screening_decisions')
    op.drop_table('screening_decisions')
    # ### end Alembic commands ###
